### ISSUE TITLE
Cannot read property createCSS of undefined

### ISSUE THREAD

**Issue by RaymondKlass** [NamPNQ/bower-videogular-flash#4]
I'm trying to set up this flash fallback for the videogular directive and am having a little trouble.  I'm seeing this error in my console:
init flash.js:57
flash.js:144
TypeError: Cannot read property 'createCSS' of undefined
    at createSWF (http://127.0.0.1:9000/bower_components/videogular-flash/flash.js:145:46)
    at init (http://127.0.0.1:9000/bower_components/videogular-flash/flash.js:58:33)
    at http://127.0.0.1:9000/bower_components/angular/angular.js:13515:28
    at completeOutstandingRequest (http://127.0.0.1:9000/bower_components/angular/angular.js:4098:10)
    at http://127.0.0.1:9000/bower_components/angular/angular.js:4404:7 

Any help would be appreciated - thanks

**Comment by dema501** [comment]
I add to index:

<pre>
&lt;script src="//cdnjs.cloudflare.com/ajax/libs/swfobject/2.2/swfobject.js"></script>
</pre>

and apply patch.

<pre>
--- flash.js_orig   2014-09-02 16:02:57.825523119 -0500
+++ flash.js    2014-09-02 16:04:06.050563858 -0500
@@ -110,7 +110,7 @@
 
                         function waitForSWF() {
-                            API.videoElement = elem.find("#videoPlayer_" + scope.playerId);
+                            API.videoElement = elem.find("object");
</pre>

because "find() - Limited to lookups by tag name"
 https://docs.angularjs.org/api/ng/function/angular.element

And your problem is gone.
